[profile.default]
solc_version = '0.8.13'
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
allow_paths= ["../../node_modules"]
src = "src"
out = "out"
bytecode_hash = "none"

[fmt]
tab_width = 2
bracket_spacing = true
