---
chains:
  - name: "localhost"
    id: "31337"
    rpc:
      http: "http://localhost:8545"
      ws: "ws://localhost:8545"
db:
  dsn: "postgresql://postgres:postgres@localhost:5432/mode_ephemeral?sslmode=disable&replication=database"
  dsnGorm: "host=localhost user=postgres password=postgres dbname=mode_ephemeral port=5432 sslmode=disable"
  wipe: true
sync:
  enabled: true
  startBlock: 0
  blockBatchCount: 10000
ql:
  port: 50091
metrics:
  port: 6060
