---
chains:
  - name: "localhost"
    id: "31337"
    rpc:
      http: "http://127.0.0.1:8545"
      ws: "ws://127.0.0.1:8545"
db:
  name: "mode_ephemeral"
  host: "localhost"
  port: 5432
  wipe: true
sync:
  enabled: true
  startBlock: 0
  blockBatchCount: 10000
ql:
  port: 50091
metrics:
  port: 6060
