[profile.default]
solc = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
allow_paths = ["../../node_modules"]
src = "src/solidity"
out = "out/solidity"
test = "test/solidity"
extra_output_files = [
  "abi",
  "evm.bytecode"
]
script_execution_protection = false