[profile.default]
# check all "WARNING:" comments before changing major solidity versions
solc = "0.8.24"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 2
allow_paths = ["../../node_modules", "../"]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
extra_output_files = [
  "abi",
  "evm.bytecode"
]
script_execution_protection = false