name: Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Install end-to-end testing dependencies
        working-directory: ./e2e
        run: pnpm install

      - name: Clean end-to-end project
        working-directory: ./e2e
        run: pnpm run clean

      - name: Build end-to-end project
        working-directory: ./e2e
        run: pnpm run build

      - name: Generate test data
        working-directory: ./e2e
        run: pnpm run generate-test-data-records

      - name: Run benchmarks
        run: pnpm run bench
