name: Snapshot release

# Releases a snapshot release when new commits merge to main
# This ensures the release process is working as expected
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"

# Ensure only one workflow/job is publishing to npm at a time
concurrency: publish-to-npm

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  release-snapshot:
    name: Publish snapshot release to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check for pre.json file existence
        id: check_files
        uses: andstor/file-existence-action@v2.0.0
        with:
          files: ".changeset/pre.json"

      # Remove this once https://github.com/changesets/changesets/issues/1195 is addressed
      - name: Temporarily exit pre-release mode to release a snapshot
        if: steps.check_files.outputs.files_exists == 'true'
        run: pnpm changeset pre exit

      - name: Clean
        shell: bash
        run: pnpm turbo run clean --force --concurrency 10

      # Build without cache to ensure we release with the most accurate output
      - name: Build
        shell: bash
        run: pnpm turbo run build --force --concurrency 10

      # The changesets action doesn't support releasing snapshots (yet),
      # so doing it manually here
      - name: Publish snapshots
        run: |
          pnpm changeset version --snapshot ${{ github.ref_name }}
          pnpm changeset publish --tag ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docker:
    uses: ./.github/workflows/docker.yml
    needs: release-snapshot

  test-snapshot:
    uses: ./.github/workflows/test-published-packages.yml
    needs: release-snapshot
    with:
      tag-or-version: ${{ github.ref_name }}
