name: Templates

on:
  push:
    branches:
      - main
  pull_request:

env:
  # Fix OOM errors with sourcemaps in phaser client
  # https://github.com/latticexyz/mud/issues/1019
  NODE_OPTIONS: --max-old-space-size=8192

jobs:
  build:
    name: Build template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: [vanilla, react, react-ecs, phaser, threejs]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Install template dependencies
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm install --ignore-scripts

      - name: Build template
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm run build

      - name: Outdated files, run `pnpm gas-report` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Run tests
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm run test
