name: Templates

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

env:
  # Fix OOM errors with sourcemaps in phaser client
  # https://github.com/latticexyz/mud/issues/1019
  NODE_OPTIONS: --max-old-space-size=8192

jobs:
  build:
    name: Build template
    strategy:
      fail-fast: false
      matrix:
        os: [depot-ubuntu-22.04-16, windows-latest]
        template: [vanilla, react, react-ecs, phaser, threejs]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        uses: ./.github/actions/build

      - name: Install template dependencies
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm install

      - name: Build template
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm run build

      - name: Outdated files, run `pnpm build` and commit them
        uses: ./.github/actions/require-empty-diff

      - name: Run tests
        working-directory: ./templates/${{ matrix.template }}
        run: pnpm run test
