name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [depot-ubuntu-22.04-16, windows-latest]

    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      local-kms:
        image: nsmithuk/local-kms
        ports:
          - 8080:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check for changes outside docs
        id: check_changes
        run: ./.github/scripts/check_changes_outside_docs.sh

      - name: Setup
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/setup

      - name: Build
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/build

      - name: Run tests
        if: steps.check_changes.outputs.changes_outside_docs
        timeout-minutes: 15
        env:
          DATABASE_URL: "postgres://postgres@localhost:5432/postgres"
          AWS_ENDPOINT_URL: "http://localhost:8080"
        run: pnpm test:ci

      - name: Generate gas reports
        if: steps.check_changes.outputs.changes_outside_docs
        run: pnpm gas-report

      - name: Outdated files, run `pnpm gas-report` and commit them
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/require-empty-diff

      - name: Sort package.json
        if: steps.check_changes.outputs.changes_outside_docs
        run: pnpm sort-package-json

      - name: Outdated files, run `sort-package-json` and commit them
        if: steps.check_changes.outputs.changes_outside_docs
        uses: ./.github/actions/require-empty-diff
